kind = "web"
previewPath = "/"
title = "Wifinity"
version = "1.0.0"
id = "artifacts/wifinity"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19941

[services.development]
run = "pnpm --filter @workspace/wifinity run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/wifinity", "run", "build" ]
publicDir = "artifacts/wifinity/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19941"
BASE_PATH = "/"
